---
title: "Leaflet Map"
author: "Chinedu, Charles, Coffy"
date: "11/23/2021"
output:
  html_document:
    code_folding: "hide"
    df_print: paged
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**Required Libraries**
```{r load-lib, message=FALSE}
# Load Libraries
library(tidyverse)
library(lubridate)
library(stringr)
library(leaflet)
library(sp)
library(ggmap)
library(leaflet.extras)
library(htmltools)
```


**Read the file**
```{r read-file, message=FALSE}
# read the file
url <- "https://raw.githubusercontent.com/chinedu2301/data607-project-gun-violence/main/Data/mass_shooting.csv"
mass_shooting <- read_csv(url)
mass_shooting <- mass_shooting %>% select(Incident_ID:lat)
```

**Check the head**
```{r}
# Look at the head of the data
head(mass_shooting)
```


**Use glimpse to check the column data types**
```{r}
# use glimpse to show the variables
glimpse(mass_shooting)
```



**Filter the dataset for each year**
```{r}
# filter the datasets for each year
ms_2014 <- mass_shooting %>% filter(year(Incident_date) == 2014)
ms_2015 <- mass_shooting %>% filter(year(Incident_date) == 2015)
ms_2016 <- mass_shooting %>% filter(year(Incident_date) == 2016)
ms_2017 <- mass_shooting %>% filter(year(Incident_date) == 2017)
ms_2018 <- mass_shooting %>% filter(year(Incident_date) == 2018)
ms_2019 <- mass_shooting %>% filter(year(Incident_date) == 2019)
ms_2020 <- mass_shooting %>% filter(year(Incident_date) == 2020)
ms_2021 <- mass_shooting %>% filter(year(Incident_date) == 2021)
```

## Mass Shootings {.tabset}  



### Mass Shooting Map  
Map of mass shooting incidents in the US from 2014 to 2021
```{r}
# Instantiate a leaflet map and plot map
leaflet() %>% addTiles() %>% 
  setView(lng = -95.7129, lat = 37.0902 , zoom = 4 ) %>%
  addCircleMarkers(data = ms_2014, lng = ~lon, lat = ~lat, radius = 1,
                   popup = ~paste0("Incident Date: ", Incident_date, "<br>",
                                   "Address: ", Geo_Address, "<br>",
                                   "Number Killed: " , No_killed, "<br>",
                                   "Number Injured: ", No_injured),
                   color = "magenta",
                   group = "2014") %>%
  addCircleMarkers(data = ms_2015, lng = ~lon, lat = ~lat, radius = 1,
                   popup = ~paste0("Incident Date: ", Incident_date, "<br>",
                                   "Address: ", Geo_Address, "<br>",
                                   "Number Killed: " , No_killed, "<br>",
                                   "Number Injured: ", No_injured),
                   color = "blue",
                   group = "2015") %>% 
  addCircleMarkers(data = ms_2016, lng = ~lon, lat = ~lat, radius = 1,
                   popup = ~paste0("Incident Date: ", Incident_date, "<br>",
                                   "Address: ", Geo_Address, "<br>",
                                   "Number Killed: " , No_killed, "<br>",
                                   "Number Injured: ", No_injured),
                   color = "green",
                   group = "2016") %>% 
  addCircleMarkers(data = ms_2017, lng = ~lon, lat = ~lat, radius = 1,
                   popup = ~paste0("Incident Date: ", Incident_date, "<br>",
                                   "Address: ", Geo_Address, "<br>",
                                   "Number Killed: " , No_killed, "<br>",
                                   "Number Injured: ", No_injured),
                   color = "brown",
                   group = "2017") %>% 
  addCircleMarkers(data = ms_2017, lng = ~lon, lat = ~lat, radius = 1,
                   popup = ~paste0("Incident Date: ", Incident_date, "<br>",
                                   "Address: ", Geo_Address, "<br>",
                                   "Number Killed: " , No_killed, "<br>",
                                   "Number Injured: ", No_injured),
                   color = "purple",
                   group = "2018") %>% 
  addCircleMarkers(data = ms_2016, lng = ~lon, lat = ~lat, radius = 1,
                   popup = ~paste0("Incident Date: ", Incident_date, "<br>",
                                   "Address: ", Geo_Address, "<br>",
                                   "Number Killed: " , No_killed, "<br>",
                                   "Number Injured: ", No_injured),
                   color = "black",
                   group = "2019") %>% 
  addCircleMarkers(data = ms_2020, lng = ~lon, lat = ~lat, radius = 1,
                   popup = ~paste0("Incident Date: ", Incident_date, "<br>",
                                   "Address: ", Geo_Address, "<br>",
                                   "Number Killed: " , No_killed, "<br>",
                                   "Number Injured: ", No_injured),
                   color = "orange",
                   group = "2020") %>% 
  addCircleMarkers(data = ms_2021, lng = ~lon, lat = ~lat, radius = 1,
                   popup = ~paste0("Incident Date: ", Incident_date, "<br>",
                                   "Address: ", Geo_Address, "<br>",
                                   "Number Killed: " , No_killed, "<br>",
                                   "Number Injured: ", No_injured),
                   color = "red",
                   group = "2021") %>% 
  addLayersControl(baseGroups = c("2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021")) 

```









